### ISSUE TITLE
Need a simple demo.

### ISSUE THREAD

**Issue by kfihihc** [DrawKit/DrawKit#1]
The DrawKit is very good framework.

I think it will be awesome if there are a simple demo. ：）

**Comment by grahammiln** [comment]
I have added the original DrawKit demonstration application both as source and a pre-built application at https://github.com/DrawKit/legacy-DrawKit-demo/releases. While not a simple example, it shows what DrawKit can do.

I believe a simple example continues to be needed.

**Comment by kfihihc** [comment]
Hi, Grahammiln,  It's great! Thanks you job.

It's benefit for any beginner.

**Comment by grahammiln** [comment]
I have added the [DKMiniDemo](https://github.com/DrawKit/legacy-DrawKit-mini-demo) project.
