### ISSUE TITLE
Load styles from file

### ISSUE THREAD

**Issue by Mediajon** [DrawKit/DrawKit#15]
Hello

I want to load styles from .styles file when button is clicked, but the result is nothing. Here is my code, can you help me to find my errors please?

    NSString *path = @"/Users/Mediajon/Documents/colors.styles";    
    [[DKStyleRegistry sharedStyleRegistry] readFromFile:path mergeOptions:kDKReplaceExistingStyles     mergeDelegate:self];

Thanks

**Comment by grahammiln** [comment]
How did you create the `colors.styles` file?

Are you able to load those styles using the [demonstration application](https://github.com/DrawKit/legacy-DrawKit-demo/releases/download/1.0b7/DrawDemo_app_b7.zip)?

Do you see any errors or messages output to your application's standard output/console?
