### ISSUE TITLE
scrollWheel jerky zoom behavior fix: event delta of 0 means 'stop gesture'

### ISSUE THREAD

**Issue by greyheli** [DrawKit/DrawKit#28]
In GCZoomView.m
- (void)scrollWheel:(NSEvent*)theEvent

      CGFloat deltaX = [theEvent deltaX], deltaY = [theEvent deltaY], deltaZ = [theEvent deltaZ];
      
      double totalDelta = deltaX + deltaY + deltaZ;
      //printf( "deltaX %f deltaY %f deltaZ %f totalDelta %f", deltaX, deltaY, deltaZ, totalDelta );
      //NSLog( @"%@", [event description] );
      if ( totalDelta == 0 )
         return; // this is the indication that a trackpad gesture has 'finished'... on the iphone, i think it means 'stop animate scroll now'

diff --git a/framework/Code/GCZoomView.m b/framework/Code/GCZoomView.m
index e78be1c..ef81021 100644
--- a/framework/Code/GCZoomView.m
+++ b/framework/Code/GCZoomView.m
@@ -421,12 +421,20 @@ NSString* kDKDrawingScrollwheelSensePrefsKey = @"kDKDrawingcrollwheelSense"; //
                // to what you might think. It's more intuitive if the centre point remains constant
 
                NSPoint p = [self centredPointInDocView];
-               CGFloat delta = [theEvent deltaY];
-
+               //CGFloat delta = [theEvent deltaY];
+
+      CGFloat deltaX = [theEvent deltaX], deltaY = [theEvent deltaY], deltaZ = [theEvent deltaZ];
+      
+      double totalDelta = deltaX + deltaY + deltaZ;
+      //printf( "deltaX %f deltaY %f deltaZ %f totalDelta %f", deltaX, deltaY, deltaZ, totalDelta );
+      //NSLog( @"%@", [event description] );
+      if ( totalDelta == 0 )
+         return; // i think this is the indication that a trackpad gesture has 'finished'... on the iphone, i think it means 'stop animate scroll now'
+      // [GCZoomView setScrollwheelInverted:YES];
                if ([[self class] scrollwheelInverted])
-                       delta = -delta;
+                       totalDelta = -totalDelta;
 
-               [self zoomWithScrollWheelDelta:delta
+               [self zoomWithScrollWheelDelta:totalDelta
                                                 toCentrePoint:p];
        } else
                [super scrollWheel:theEvent];

**Comment by grahammiln** [comment]
Thank you. Please can you provide a [pull request](https://help.github.com/articles/using-pull-requests/) so I can review and merge this in for you.
