### ISSUE TITLE
Carthage support for DrawKit?

### ISSUE THREAD

**Issue by JetForMe** [DrawKit/DrawKit#30]
I really like Carthage over Cocoapods. Any chance you could add support for Carthage? I like that it leaves my project files alone.

**Comment by grahammiln** [comment]
I have no experience with [Carthage](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework). Is much work needed on DrawKit to support Carthage?

**Comment by grahammiln** [comment]
[DrawKit v1.0.3 now supports Carthage](https://github.com/DrawKit/DrawKit/releases/tag/v1.0.3).

Does this work for you?

**Comment by JetForMe** [comment]
Probably! Chatting with Graham Cox, I decided to try my little app without DrawKit for the time being, but I really appreciate the quick turnaround. I'll let you know how it goes.
