### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by slcott** [DrawKit/DrawKit#31]
I tried using the library in a swift project and converting the example project [DK Mini Demo](https://github.com/DrawKit/legacy-DrawKit-mini-demo) to swift. I'm running into a few errors. The first is `Value of type 'DKDrawingView' has no member 'selectDrawingTool'`. Looks like the way the obj-c code is written, those methods appear private. Attached is the project.
[DrawingView.zip](https://github.com/DrawKit/DrawKit/files/1097479/DrawingView.zip)

**Comment by smspence** [comment]
I tried adding DrawKit to a brand new (blank) Swift project using Cocoapods. Here is what my Podfile looks like:

```
platform :osx, '10.11'

target 'WFStudio' do
  use_frameworks!

  pod "DrawKit"

end
```

After running `pod install` and opening up the .xcworkspace file, I cannot seem to actually using any of the DrawKit classes in my Swift code.  This is strange.  Is there something I am missing?

Should I be able to create a Swift class that subclasses `DKViewController`? I have tried doing an `#import DrawKit`, `#import DKDrawKit`, `#import DKViewController`, etc. all to no avail.

**Comment by smspence** [comment]
In the Objective-C code, it looks like the method `selectDrawingToolByName` belongs to the class `DKToolController`, not `DKDrawingView`.

But in the original code for [legacy-DrawKit-mini-demo](https://github.com/DrawKit/legacy-DrawKit-mini-demo), it looks like it is able to call that method on a `DKDrawingView` object. I'm not sure how this is possible. I am confused.

**Comment by smspence** [comment]
Try this:
```
    @IBAction func toolMatrixAction(_ sender: NSMatrix) {
        // the drawing view can handle this for us, provided we pass it an object that responds to -title and returns
        // the valid name of a registered tool. The selected button cell is just such an object.
        let cell: NSButtonCell? = sender.selectedCell() as! NSButtonCell

        let toolController : DKToolController = mDrawingView.controller() as! DKToolController

        toolController.selectDrawingToolByName(cell)
    }
```

I think that is what you want to do.  Or at least it gets you a little closer to being able to compile your project... :)

**Comment by grahammiln** [comment]
@smspence if you would like to [push the appropriate code fix](https://help.github.com/articles/requesting-a-pull-request-review/) to DrawKit, I can commit the change and credit your contribution.

**Comment by grahammiln** [comment]
I have merged in a large change from [MaddTheSane](https://github.com/MaddTheSane) that begins Swift support. Hopefully this will provide a base to continue development from.
