### ISSUE TITLE
Where's the right place to instantiate `DKUndoManager`?

### ISSUE THREAD

**Issue by fblecha** [DrawKit/DrawKit#36]
I'm porting the legacy mini demo to xcode9/swift 4/storyboards and everything builds.  However, I'm getting hit with [the assert that the undo manager hasn't been setup yet](https://github.com/DrawKit/DrawKit/blob/2b571d79b93ce4234ee8fe9a30228543551f877f/Source/DKDrawingView.m#L273) .  

I've got the DKUndoManager singleton created in the default ViewController.  

Where's the recommended place to assign it prior to calling  createAutomaticDrawing() ?

**Comment by MaddTheSane** [comment]
The Mini Demo app implements an `NSWindowDelegate` method `-windowWillReturnUndoManager:`. There may be problems if `-createAutomaticDrawing` is called before it is put in a window.
