### ISSUE TITLE
Question - SVG support?

### ISSUE THREAD

**Issue by fblecha** [DrawKit/DrawKit#38]
Is SVG supported now (2018)?  I saw a [note from 2014](https://github.com/DrawKit/DrawKit/issues/6) that said that PDF is supported and go that route or make your own converter.  I'm assuming that's still the case but wanted to clarify.

**Comment by grahammiln** [comment]
I do not believe anyone is actively working on SVG support and I have not seen a fork with the feature.

Given that, exporting to SVG is not included but, as mentioned in #6, should not be too difficult to implement for most shapes.

**Comment by fblecha** [comment]
@grahammiln seems like svg -> pdf -> asset -> NSImage should work ?

**Comment by grahammiln** [comment]
What are you hoping to achieve? If the end goal is a scalable format usable with `NSImage`, take a look at [`DKDrawing's pdf`](https://github.com/DrawKit/DrawKit/blob/db7b22040986e24c4c9f15ec1ceb7c22c0b14503/Source/DKDrawing.h#L633) method.

**Comment by fblecha** [comment]
For future me and others, here's a way you can go:

1. Create a new asset, add a PDF image as a universal asset.
2. Convert your SVG -> PDF
3. Add your PDF to your asset from (1)
4. Use the following code:

```swift
    let image = //MyImageLiteral or any NSImage
    let shape: DKImageShape = DKImageShape(image: image)
    shape.imageKey = "123456"  //need to figure out what key means here, likely guid
    shape.location = NSPoint(x: 100, y: 100)  //hardcoded, but malleable 
    
    guard let dwg = mDrawingView.drawing else { return }
    guard let layer = dwg.layers(of: DKObjectDrawingLayer.self).first else {return}
    layer.addObject(shape)
```
