### ISSUE TITLE
Xcode 10 / Mojave / Swift 4.2 issue?

### ISSUE THREAD

**Issue by fblecha** [DrawKit/DrawKit#42]
I'm getting a black rendering for my view on something that was previously working after upgrading to:
- Xcode 10 (app store version)
- Mojave
- Swift 4.2

I'm downloading Xcode 9.4.1 to see if that's the issue and am going to step through it.

Anyone else seeing this?

**Comment by MaddTheSane** [comment]
IIRC, anything that calls `lockFocus` to a view don't work on Mojave. I had something similar happen on my NetHack3D branch, and I think DrawKit uses `lockFocus`.

**Comment by fblecha** [comment]
any work around you'd suggest @MaddTheSane ?  I'm used to looking at DrawKit internals, but I haven't tried modifying it at all.  Is that the route that's going to have to happen for mojave support?

**Comment by fblecha** [comment]
Ok, the following works:
- swift 4.1.2
- xcode 9.4.1
- **Mojave**

**Comment by MaddTheSane** [comment]
My guess is the targeting of the Mojave SDK. 9.4.1 targets the High Sierra SDKs, and Mac OS X does some trickery to make sure apps built against older SDKs still work somewhat.

**Comment by fblecha** [comment]
@MaddTheSane  been a while since I worked on the project that used this -- did the change you implemented with https://github.com/DrawKit/DrawKit/commit/ff220d62a08533291c2cb7cecb5c9548c6ab95f7 means it should work with Xcode 10 now?

**Comment by MaddTheSane** [comment]
It should.

**Comment by fblecha** [comment]
confirm it works - we should tag a new release @MaddTheSane @grahammiln - 1.0.4?
