### ISSUE TITLE
How to access image that was dragged into DKDrawingView[Help Needed]

### ISSUE THREAD

**Issue by calebmitcler** [DrawKit/DrawKit#43]
How can i access and resize an image that was dragged into DKDrawingView. I need to resize the image to fit the view. The functionality i'm looking for can be found in the GCDrawDemo, the object inspector window

```
//get the layer the current image is at
let obj = canvasDrawing.objectInLayers(at: 1)
//bitmaprepresentation of that image
let bitmaprep = obj.bitmapRepresentation(withDPI: 350)
 let nsImg =  NSImage.init(cgImage:  (bitmaprep.cgImage)!, size: NSSize.init(width: 3000.0, height: 1200))
```

right now this produces an image thats cropped to fit the DKDrawingView canvas

**Comment by grahammiln** [comment]
Please could you add screenshots to show the behaviour and another for the desired output?

**Comment by calebmitcler** [comment]
when i drag in a very large photo
![image](https://user-images.githubusercontent.com/12163096/49745613-63c09380-fc6d-11e8-8499-278de1561038.png)

i'd like to be able to auto scale the photo to fit the dkdrawingview.
![image](https://user-images.githubusercontent.com/12163096/49745890-fc571380-fc6d-11e8-873c-59a71de84df0.png)

 it appears from the demo this functionality is in DKImageShape class but i'm not sure how to derive these functions from the layer/object that was just added. currently i'm using hit test to get the object that was added but this is not right .
`var canvasDrawing:DKDrawing!`
.
.
`let obj = canvasDrawing.objectInLayers(at: 1)`
` let drawableObj = obj.hitTest(NSPoint.init(x: 100.0, y: 100.0))`
`drawableObj?.resizeBy(width: 0.1, height: 0.1)`

so i need some kind of delegate method that is called when an object is dropped into the view. i'm already implementing DKDrawingDelegate methods, but i don't think any of these notify when an object is added. then i need to reference that object some way other than using hittest

**Comment by calebmitcler** [comment]
Awesome. Thank you!
