### ISSUE TITLE
Implementation of DKSecretSelectorsDrawingLayer.

### ISSUE THREAD

**Issue by manuel1414** [DrawKit/DrawKit#49]
I can not find the implementation of DKSecretSelectorsDrawingLayer, exist or I need work on them to implement.

**Comment by grahammiln** [comment]
The history of individual lines is available using the `blame` feature of `git` or GitHub. Using this ability it appears these methods need removed or re-implemented.

`DKSecretSelectorsDrawingLayer` appeared in the January 2018 commit: [Move the DKSecretSelectors to their own (unimplemented) interfaces.](https://github.com/DrawKit/DrawKit/commit/1a96544726ebf70bfdf42d1a44ed0f2ad140de0b)

These methods were likely related to the Generic Polygon Clipper ([gpc.h](https://github.com/DrawKit/DrawKit/blob/1.0.0-beta-7/framework/ThirdParty/gpc/gpc.h)) non-commercial use code that I removed before moving to the MPL licence.

**Comment by manuel1414** [comment]
Thanks. GPC library is not longer available, instead I will work in a implementation using ClipperLib "http://www.angusj.com/delphi/clipper.php" that use Boost Software License.

Manuel :)
