### ISSUE TITLE
Convert to Shape Group bug

### ISSUE THREAD

**Issue by Mediajon** [DrawKit/DrawKit#7]
Hi

When converting text into Shape Group, line which is below is going top and top line is going to bottom as attached image.

Thanks
![textgroup](https://cloud.githubusercontent.com/assets/4078826/5488957/38b02562-86e6-11e4-8606-205030c125b6.png)

**Comment by Mediajon** [comment]
Found the problem when converted to Shape Group changing places. Now, converted objects are on the same location. But still cannot fix the second problem (where additional characters appear at the end of line).

**Comment by grahammiln** [comment]
That is good news. Please can you share what you fixed here or in a pull request?

Maybe someone will come along and be able to help with the appended character portion.

**Comment by Mediajon** [comment]
Hi

Only you should delete "-" sign from line 58 of DKBezierLayoutManager.m.

ploc.x -= fragRect.origin.x;
ploc.y = fragRect.origin.y;

Original is:

ploc.x -= fragRect.origin.x;
ploc.y -= fragRect.origin.y;
